export const users = [
    {
        id: 0,
        name: "Mark Twen",
        avatar: "avatar-male.png",
        pubDate: "Today, 12:00",
        rating: 3.9,
        comment: "This is awesome adventure that I had! Thanks!",
        category: "ADVENTURE BLOG",
        email: "mark.twen@example.com",
        password: "mark1234",
        age: 35,
        posts: [
            {
                title: "A Great Adventure",
                date: "Today, 11:00",
                content: "Exploring new places is always fun.",
            },
            {
                title: "Road Trip",
                date: "Yesterday, 14:00",
                content: "Visited some amazing spots along the way.",
            },
        ],
    },
    {
        id: 2,
        name: "Alice Johnson",
        avatar: "avatar-female2.png",
        pubDate: "1 week ago, 16:45",
        rating: 4.8,
        comment: "Beautiful scenery and peaceful environment.",
        category: "NATURE BLOG",
        email: "alice.johnson@example.com",
        password: "alice7890",
        age: 32,
        posts: [
            {
                title: "A Walk in the Forest",
                date: "2 days ago",
                content: "It was so relaxing to walk among the trees.",
            },
            {
                title: "Mountain Views",
                date: "1 week ago",
                content: "Breathtaking views from the top.",
            },
        ],
    },
    {
        id: 3,
        name: "Sally Robinson",
        avatar: "avatar-female2.png",
        pubDate: "Yesterday, 18:30",
        rating: 4.6,
        comment: "Something new for me. Drive and emotions only.",
        category: "FASHION BLOG",
        email: "sally.robinson@example.com",
        password: "sally7890",
        age: 27,
        posts: [
            {
                title: "New Trends",
                date: "Yesterday",
                content: "Exploring the latest fashion trends.",
            },
            {
                title: "Style Tips",
                date: "2 days ago",
                content: "Mix and match to find your personal style.",
            },
        ],
    },
    {
        id: 4,
        name: "Katherine Johns",
        avatar: "avatar-female.png",
        pubDate: "5 days ago, 12:15",
        rating: 4.0,
        comment: "The place is very big. I lost the exit.",
        category: "ADVENTURE BLOG",
        email: "katherine.johns@example.com",
        password: "katherine5678",
        age: 28,
        posts: [
            {
                title: "Lost in the Woods",
                date: "3 days ago",
                content: "A thrilling but scary experience.",
            },
        ],
    },
    {
        id: 5,
        name: "Bob Brown",
        avatar: "avatar-male2.png",
        pubDate: "2 weeks ago, 10:30",
        rating: 4.2,
        comment: "Great place to relax and unwind.",
        category: "NATURE BLOG",
        email: "bob.brown@example.com",
        password: "bob4567",
        age: 40,
        posts: [
            {
                title: "Beach Day",
                date: "3 days ago",
                content: "Relaxed by the shore, enjoyed the sunset.",
            },
        ],
    },
    {
        id: 6,
        name: "John Doe",
        avatar: "avatar-male2.png",
        pubDate: "1 month ago, 14:00",
        rating: 4.1,
        comment: "Had a great time exploring new places.",
        category: "ADVENTURE BLOG",
        email: "john.doe@example.com",
        password: "john1234",
        age: 31,
        posts: [
            {
                title: "Exploring Europe",
                date: "1 month ago",
                content: "Visited several countries in Europe.",
            },
        ],
    },
    {
        id: 7,
        name: "Emily Clark",
        avatar: "avatar-female2.png",
        pubDate: "3 weeks ago, 10:00",
        rating: 4.5,
        comment: "Loved the cultural experiences.",
        category: "NATURE BLOG",
        email: "emily.clark@example.com",
        password: "emily5678",
        age: 26,
        posts: [
            {
                title: "Cultural Fest",
                date: "3 weeks ago",
                content: "Participated in a local cultural festival.",
            },
        ],
    },
    {
        id: 8,
        name: "Michael Scott",
        avatar: "avatar-male.png",
        pubDate: "2 months ago, 08:00",
        rating: 4.7,
        comment: "Amazing experience with friends.",
        category: "FASHION BLOG",
        email: "michael.scott@example.com",
        password: "michael7890",
        age: 38,
        posts: [
            {
                title: "Friends Reunion",
                date: "2 months ago",
                content: "Reunited with old friends.",
            },
        ],
    },
    {
        id: 9,
        name: "Laura Wilson",
        avatar: "avatar-female.png",
        pubDate: "1 week ago, 12:00",
        rating: 4.3,
        comment: "Great insights on health and wellness.",
        category: "ADVENTURE BLOG",
        email: "laura.wilson@example.com",
        password: "laura1234",
        age: 29,
        posts: [
            {
                title: "Healthy Living",
                date: "1 week ago",
                content: "Tips for a healthy lifestyle.",
            },
        ],
    },
    {
        id: 10,
        name: "David Miller",
        avatar: "avatar-male.png",
        pubDate: "2 days ago, 15:00",
        rating: 4.9,
        comment: "Fantastic tech reviews.",
        category: "NATURE BLOG",
        email: "david.miller@example.com",
        password: "david5678",
        age: 33,
        posts: [
            {
                title: "Latest Gadgets",
                date: "2 days ago",
                content: "Reviewed the latest tech gadgets.",
            },
        ],
    },
    {
        id: 11,
        name: "Sophia Davis",
        avatar: "avatar-female.png",
        pubDate: "3 days ago, 11:00",
        rating: 4.4,
        comment: "Great recipes and cooking tips.",
        category: "FASHION BLOG",
        email: "sophia.davis@example.com",
        password: "sophia7890",
        age: 27,
        posts: [
            {
                title: "Delicious Recipes",
                date: "3 days ago",
                content: "Shared some delicious recipes.",
            },
        ],
    },
    {
        id: 12,
        name: "James Brown",
        avatar: "avatar-male2.png",
        pubDate: "5 days ago, 09:00",
        rating: 4.2,
        comment: "Interesting insights on finance.",
        category: "ADVENTURE BLOG",
        email: "james.brown@example.com",
        password: "james1234",
        age: 36,
        posts: [
            {
                title: "Investment Tips",
                date: "5 days ago",
                content: "Shared some valuable investment tips.",
            },
        ],
    },
    {
        id: 13,
        name: "Karen Lee",
        avatar: "avatar-female.png",
        pubDate: "8 months ago, 09:30",
        rating: 4.6,
        comment: "Fantastic!",
        category: "NATURE BLOG",
        email: "karen.lee@example.com",
        password: "karen7890",
        age: 30,
        posts: [
            {
                title: "Yoga for Beginners",
                date: "7 months ago",
                content: "Easy yoga poses to get started.",
            },
        ],
    },
    {
        id: 14,
        name: "Jane Smith",
        avatar: "avatar-female.png",
        pubDate: "4 days ago, 11:00",
        rating: 4.8,
        comment: "Absolutely loved it!",
        category: "FASHION BLOG",
        email: "jane.smith@example.com",
        password: "jane1234",
        age: 34,
        posts: [
            {
                title: "Running Tips",
                date: "4 days ago",
                content: "Improved my running with these tips.",
            },
        ],
    }
]